### ISSUE TITLE
display_window doesn't match original OpenEXR implementation

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#120]
On a simple 16x16 EXR image, `exrheader` shows: 

```
dataWindow (type box2i): (0 0) - (15 15)
displayWindow (type box2i): (0 0) - (15 15)
```

But on `exrs`, `meta_data.headers[0].shared_attributes.display_window` is this:

```
display_window (box2i): (0, 0) - (16, 16)
```

I suspect the `exrs` implementation skip the last row/column. But I think it shouldn't work like the and the box should be 0-15.

**Comment by johannesvollmer** [comment]
In the cop version, the bounds are inclusive. For 16 elements, the upper bound is 15.

In Rust (and also in C++, actually) the convention is different. The larger bounds in Rust ranges and indices are exclusive. For 16 elements, the upper bound is 16.

I chose to go with the rust convention instead of the C++ exr convention. If you want to output stats that obey the C++ exr conventions, you will have to subtract 1 from the bounds.

**Comment by johannesvollmer** [comment]
This should be described in the documentation of the IntegerBounds: https://docs.rs/exr/1.1.0/exr/meta/attribute/struct.IntegerBounds.html

**Comment by Narann** [comment]
Thanks!

**Comment by johannesvollmer** [comment]
Also, the original library will use min and max values, whereas the Rust version has position and size. You can use `bounds.position` and `bounds.max()` to obtain the exact values which the original library would use :)

**Comment by Narann** [comment]
I moved to another description :

```
display_window (integer bounds): position: (0, 0), size: 16x16
```

**Comment by johannesvollmer** [comment]
Maybe we should rename the `IntegerBounds.position` to `.bottom_left` in the whole crate. What do you think? Position could also be interpreted to be the center of the image.

**Comment by Narann** [comment]
`bottom_left` would make sense if combined with `top_right`. This is a bounding box definition (aka "limits"). The reason you would want this is related to how you use those data.

If you always use bounding box, it's better to always use `bottom_left`/`top_right` as you may save many additions when you work. This could avoid: `position.x..(position.x+size.x)`.

If you ask me, I would stick with the Box original implementation: Box is composed of two points: `min` and `max`:

https://www.openexr.com/documentation/openexrfilelayout.pdf#page=14

I'm not an experimented programmer, but I think min/max (aka, "limits") is better when you code.

If you need dimension (it should be less frequent than limits) implement a `Box2d.dimension()` returning a Point2d (or a tuple).

2D Box are similar to 3D Box: 2 points, only the point dimension change.

OpenEXR standard is quite tied to Imath and have many 1:1 Imath structures in it. I suggest to not move too far from how those datas are represented *and* add convenient functions around the original one.

An interesting convenient function to add would be a `Box2d.x_iter()` and `Box2d.y_iter()` to iter around each row/column.

My 2 cts.

Keep the good work ! :)

**Comment by johannesvollmer** [comment]
Good points. 

Background: The reason for the current data structure was that it cannot possibly have an invalid state. In contrast, the min/max approach could be invalid suddenly, by accidentally having min with a greater value than max. That's why the rust approach would be to minimize errors, even if this means that you have to do `position + size` (`bound.max(), bounds.end()`) sometimes. You can't accidentally break the whole crate by assigning and invalid value.

The alternative would be to have min/max and then add thousands of getters and setters, which seems pretty overkill for such a simple data structure, and is not desired in Rust


In general, I think it's worth to embrace the rust patterns and get away from the original implementation, as otherwise you could just use the C++ Rust Bindings, which are very close to the original. If this library did not do anything differently than the bindings, there would be no reason to use it :D Also, I think the original library has quite some rough corners

**Comment by Narann** [comment]
As you wish! :)
