### ISSUE TITLE
Release new version with miniz_oxide v0.7.1?

### ISSUE THREAD

**Issue by stephanemagnenat** [johannesvollmer/exrs#212]
Recently the dependency to miniz_oxide has been updated to 0.7.1, the latest version.

Would it be possible to do a minor release with this updated dependency? This would allow the image package, which currently depends on miniz_oxide v0.6.2 only through exr, to remove one duplicated dependency, which would be useful in the embedded/WASM world.

**Comment by johannesvollmer** [comment]
Yes. Due to miniz_oxide not being at `v1.x.x` yet, it cannot be upgraded automatically. This is because in SemVer, minor version upgrades are considered breaking when the crate's version starts with a zero. For this reason, is is required for us to publish a new version of exr. I previously didn't realize this, I thought it was a minor change that could automatically be upgraded in the image create, sorry :)

**Comment by johannesvollmer** [comment]
it's done :) 
https://crates.io/crates/exr/1.6.4/dependencies

**Comment by stephanemagnenat** [comment]
Thank you!
