### ISSUE TITLE
Test suite not portable

### ISSUE THREAD

**Issue by mandeep** [johannesvollmer/exrs#32]
The test suite images are stored in a local directory it seems. I think they should be added to the `tests` dir so that way everyone can run them.

In the meantime, I've been trying my application out on https://github.com/AcademySoftwareFoundation/openexr-images/ and I think `exrs` could benefit from testing on these images as well.

**Comment by johannesvollmer** [comment]
Hi, thanks for your issue. I have been testing with the repository that you linked to locally. Those images are all producing the expected output on my machine. 

Those images are not yet included in this repository because I was not quite sure if it was good practice to include such a large folder. Alternatively, a build script could download the images repository into a local folder before building. Which solution would you prefer? Maybe there's even more possibilities.

**Comment by johannesvollmer** [comment]
Actually, I've been using a really old clone of the images repository, excluding the damaged image folder.

**Comment by johannesvollmer** [comment]
I just tried simply putting all images into a folder and adding it to this repository. It worked, without the need for any large file support. That's why I came to the conclusion that this would be the easiest solution. Pushing took quite a while tough, haha, and cloning will probably take some more time now, too. It's a start 🎉

**Comment by johannesvollmer** [comment]
@mandeep, I would appreciate if you'd find the time to test if the test suite now works as expected (expect some tests to fail, I just discovered a few new bugs).

**Comment by mandeep** [comment]
It looks like the image files are now found. However, I have a failure with `test_write_file`.

One thing to note is that instead of copying the images directory over into your repo, you can use git submodules to obtain a similar effect. The benefit of submodules is that you don't have to copy over the images every time there is an update. You can just call `git submodule update` to update the linked images repo.

**Comment by johannesvollmer** [comment]
Thanks for the submodule hint. I'll investigate on that. Can you give me some more information about the failed test? Is there a panic message or an Error?

**Comment by mandeep** [comment]
Here's the output from cargo test: https://gist.github.com/mandeep/e3706560fb21afbb48d1e7134468ffc6

**Comment by johannesvollmer** [comment]
Ok. So in `dev.rs` on line 48 there's a file path string. The test must read that file and write it into another directory. Can you check if that file exists in your project? It seems like this file cannot be found and maybe that file was not commited or maybe there's a typo in the path.

```rust
let path = "tests/images/valid/openexr/BeachBall/multipart.0001.exr";

let image = Image::read_from_file(path, read_options::high()).unwrap();
Image::write_to_file(&image, "tests/images/out/written.exr", write_options::high()).unwrap();
```

**Comment by johannesvollmer** [comment]
Actually, this specific test was not an official test but rather development stuff. 

I've made a few changes to the rgba API, would you like to give me some feedback on the design?

**Comment by mandeep** [comment]
Thanks, I'm indeed working off the git repository. After a pull from upstream `cargo test --no-fail-fast` shows that all tests pass. :)

I'll take a look at the API and I'll make a new post with any issues I find. Thanks for taking the time to do all of this!

**Comment by johannesvollmer** [comment]
Perfect! Thank you.
