### ISSUE TITLE
Set data window x,y coordinate using simple Layer

### ISSUE THREAD

**Issue by bryab** [johannesvollmer/exrs#45]
First of all, thank you for this library.  It's a huge improvement from the native openexr bindings.

I am trying to make a relatively simple tool, and would like to use your "simple" system here to do it.  Almost everything is working great, and I appreciate not having to write the headers myself.  But the one thing I would like to have access to is the data window x,y position for each layer.  Is it possible to set this without going into the "full" set of tools?

**Comment by johannesvollmer** [comment]
Thanks! Yes, this is possible. The data window position is contained inside the `LayerAttributes`. 

In order to set these, it's currently necessary to manually set them directly (there is not yet a setter method):
```rust
let mut layer: simple::Layer = ...;
layer.attributes = LayerAttributes {
    data_position: Vec2(3, -5),
    .. LayerAttributes::default()
}
```

Does this help you? Where would you expect to find this information about layer attributes? Together we can improve the documentation of this crate so that other people do not have to wait for an answer from me :)

**Comment by bryab** [comment]
D'oh, I'm a Rust newbie and my problem was simply that I did not make it `mut`.  Thank you.  I guess if you had a bit more information in the "simple write" example, such as changing parameters like this, that would have led me in the right direction.

I would also suggest a version of your "extract pngs" script that uses the simple method, if possible.

Thanks again.

**Comment by johannesvollmer** [comment]
Thanks for your suggestions, I'll make something happen! :+1:

**Comment by bryab** [comment]
Hey, one other question.  Do you have any recommendations of optimizations when loading many images in sequence?  If they all share the same channels and size?  For example, could a shared image buffer be used for them all?

**Comment by johannesvollmer** [comment]
I assume you can only gain a very small performance win by reusing buffers. I can't think of anything that would optimize processing many images in sequence... I'd recommend to analyze and profile the running app in order to find a specific bottleneck.

If it the buffer allocation turns out to be a real issue, I can do something about that and add some API to allow for customizing (and reusing) that allocation. 

If you want to speed up the reading of exr images in general, try to only work with uncompressed images. The compression algorithms are the bottleneck most of the time.
