### ISSUE TITLE
optimization prevents debug_assert

### ISSUE THREAD

**Issue by johannesvollmer** [johannesvollmer/exrs#79]
The [documentation](https://doc.rust-lang.org/cargo/reference/profiles.html) says that `opt-level = 3` disables debug assertions, which may have resulted in many checks not being performed?

**Comment by dgsantana** [comment]
I believe that is correct. I normally leave the default for debug builds, only the release build do I squeeze the options. I normally, even make `panic = abort` since most of the work I do is dynamic rust libraries with C ABI exposed normally to call from Python (with c_types) or C#, of course that doesn't apply here.

**Comment by johannesvollmer** [comment]
I set `opt-level = 3` for dev builds to make the tests run in reasonable time. So this means that we have to set it to `0`, right? With very slow testing speed?

**Comment by dgsantana** [comment]
There is supposed to be a `[profile.test]`. It's also possible to call `cargo test --release`, where test uses the `profile.release` for compiling. Of course, if you want to catch those asserts in tests, well then `opt-level = 0` is the right answer.

**Comment by johannesvollmer** [comment]
That's sad. I want safety __and__ speed. :(

**Comment by johannesvollmer** [comment]
Level set to 0 in dev branch
