### ISSUE TITLE
Add support for missing common attributes

### ISSUE THREAD

**Issue by virtualritz** [johannesvollmer/exrs#83]
Specifically I miss `near`, `far`, `fieldOfView*` & `software` from below list (which is a common EXR from a professional 3D production offline renderer). 

```
exrheader out_noise.exr

file out_noise.exr:

file format version: 2, flags 0x0
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
compression (type compression): zip, multi-scanline blocks
dataWindow (type box2i): (0 0) - (2047 2047)
displayWindow (type box2i): (0 0) - (2047 2047)
far (type float): 1e+38
fieldOfViewHorizontal (type float): 30
fieldOfViewVertical (type float): 30
lineOrder (type lineOrder): increasing y
near (type float): 0.001
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
software (type string): "3Delight 2.1.9 darwin-x86_64 (Jun 24 2020, 2a265d) "Re-Animator""
type (type string): "scanlineimage"
worldToCamera (type m44f):
   (1 0 0 0
    0 1 0 0
    0 0 1 0
    0 0 0 1)
worldToNDC (type m44f):
   (3.73205 0 0 0
    0 3.73205 0 0
    0 0 1 1
    0 0 -0.001 0)
```

**Comment by johannesvollmer** [comment]
As a workaround, use `attributes.custom` until the mentioned Attributes are added - it will contain all attributes that are not in the attributes struct

**Comment by virtualritz** [comment]
Yes, I thought this could work too.

On a side note: `fieldOfViewHorizontal` and `fieldOfViewVertical` are redundant when `worldToCamera` and `worldToNDC` are specified. At least in the non-anamorphic case. Actually, I'm not 100% certain that this doesn't apply in all cases. So it would probably be good to have a utility function like below to add them to `LayerAtrributes` when those already have the two `world_to_*` matrices defined.

Here is some C++ code to calculate them (with best regards from the 3Delight developers):

```c++
void AddFieldOfView( Imf::Header &header )
{
	try
	{
		const Imf::M44fAttribute &w2Cam =
				header.typedAttribute<Imf::M44fAttribute>( "worldToCamera" );
		const Imf::M44fAttribute &w2NDC =
				header.typedAttribute<Imf::M44fAttribute>( "worldToNDC" );
		/* No FOV if it isn't perspective projection. */
		if( w2NDC.value()[2][3] == 0.0f )
			return;

		Imath::V4f v =
				Imath::V4f( 1.0f, 1.0f, 0.0f, 0.0f ) *
				w2NDC.value().gjInverse() * w2Cam.value();
		float hfov = atanf( v.x ) * 2.0f * float(180.0 / M_PI);
		float vfov = atanf( v.y ) * 2.0f * float(180.0 / M_PI);
		header.insert( "fieldOfViewHorizontal", Imf::FloatAttribute( hfov ) );
		header.insert( "fieldOfViewVertical", Imf::FloatAttribute( vfov ) );
	}
	catch( std::exception & )
	{
	}
}
```

**Comment by johannesvollmer** [comment]
Nice. 

Concerning the extraction of parameters from view matrices, I think the code snippet will definitely be useful. 

However, although the original OpenEXR C++ library contains a lot of those helpers, `exrs` focuses mainly on file encoding and decoding. I'm sure matrices calculations can already be done with common linear algebra crates and. Also, when writing an image, I would assume the field of view is directly available to the caller, as an existing variable. 

That's why I think adding this method and other helpers, albeit helpful to some users, would eventually blow up compilation times and increase the maintenance costs. 

An alternative option would be to offer an explicit setter for all camera related attributes, such that none of the common attributes can be forgotten when writing a file:

```rust
fn with_camera(ndc: matrix4x4, fov: f32, near: f32, far: f32, ...)
```

As a second alternative, I can imagine initiating a second crate that contains helpers like color conversion, mipmap generation, matrix calculations and more.

**Comment by virtualritz** [comment]
Good points. Maybe just incorporate that code into one of the samples/docs of `exrs`?

I edited the above comment and replaced the C++ with some Rust that uses `cgmath` and which I use in my display driver.
