### ISSUE TITLE
Use RgbaImage API for "old school" layers within EXR

### ISSUE THREAD

**Issue by bryab** [johannesvollmer/exrs#91]
I have EXRs that do not use EXR 2.0 layers, but instead just have channel names with the following syntax:

Layer1.R
Layer1.G
Layer1.B
...

I really like the convenience of the "rgba" api you made for dealing with simple RGBA EXRs.  Is there some way to use this API but for the "layers" within a multichannel EXR? I am specifically interested in using the `read_pixels_from_file` function to easily read and write pixels from RGBA channels.  Thanks!

**Comment by johannesvollmer** [comment]
Hi! This is not possible with the current api. As a work around, you can use the "simple image" api and manually check for RGB channels. The great api rework, which is currently in development, will support that eventually. 

I didn't have much time in last months, that's why the new api didn't progress too much. I hope I can take some time the next week's to finalize that design.

**Comment by bryab** [comment]
Thanks!
