### ISSUE TITLE
Create Image from a [Layer] slice, not only smallvec

### ISSUE THREAD

**Issue by virtualritz** [johannesvollmer/exrs#97]
## What can be improved or is missing?
When I'm writing out multi-layer EXR data I am looping over my pixel format and dissect that into individual `Layer`s.
What I end up is always a `Vec<Layer>`.

## Proposal
It would be great if there was a constructor or method on `Image` that would just take a slice of `[Layer]`s and do the right thing™. Maybe `Image::from_layers()`?

## Alternatives
Some way to  add a single layer to an Image. It seems this is only possible if the `Image` consists of just one Layer as in `from_single_layer()`. 

--------------
P.S.: I would rename `from_single_layer()` to `from_layer()` – the use of a weasel word doesn't add clarity here. You only get *one* `Image` back from putting *one* `Layer` in. That's obvious from the signature.

**Comment by johannesvollmer** [comment]
> Image that would just take a slice of [Layer]s

A function like this exists, but it might be a little bit hard to find, because it has a generic parameter: [`Image::new`](https://docs.rs/exr/1.0.0/exr/image/struct.Image.html#method.new) :)

This means you can pass either a single `Layer` or a [a `smallvec` of `Layer`s](https://docs.rs/exr/1.0.0/exr/image/type.Layers.html) object: `Image::new(ImageAttributes::default(), smallvec![ layer1, layer2 ])`.

Note that it currently must be an owning `smallvec` and not a slice or a normal `vec`. I'll change it to accept any `impl AsRef[Layer]`, which would allow us to pass a slice instead of a `smallvec ` here, it should be a simple change.

I recognize that it might be hard to see through these generics all over the place. I've written some documentation but it's not merged into master yet. In addition, we could of course add another function, not called `new`, but `from_layers`, which would take a slice or vector of layers, without a generic type. 

---
> I would rename from_single_layer() to from_layer()

Agreed :)

**Comment by johannesvollmer** [comment]
Does this help? :) 
Please do leave this Issue open either way, until I push the planned changes.

**Comment by virtualritz** [comment]
Yes, I actually found this out myself, last night, while looking through the crate source. :]
