### ISSUE TITLE
Improve arbitrary channels per layer

### ISSUE THREAD

**Issue by virtualritz** [johannesvollmer/exrs#98]
## What can be improved or is missing?
I'm getting other data than just RGB(A) from my renderer. Currently the crate seems to only support RGB and RGBA pixel formats.

I currently use RGB for Y, single channel (red = Y, blue & green zero) or RGBA for YA (red = Y, blue and green zero, alpha = A).
I also have 4 channels (+ optional alpha = 5 channels). The latter I can't even 'squeeze' into an RGBA pixel any more.

**Comment by johannesvollmer** [comment]
The crate does support an arbitrary number of layers, in multiple ways. Have a look at the [`3_simple_write` example](https://github.com/johannesvollmer/exrs/blob/master/examples/3_simple_write.rs). Although this example uses RGBA channels, it shows how to use the mechanism which supports arbitrary channels :)

Your code might look like this:
```rust
    let y = AnyChannel::new("Y", FlatSamples::F32(vec![0.0; pixel_count]));
    let a = AnyChannel::new("A", FlatSamples::F32(vec![0.0; pixel_count]));
    
    let layer = Layer::new(
        resolution,
        LayerAttributes::named("luma and alpha"),
        Encoding::FAST_LOSSLESS,

        // here we pass the list of channels we want in our image, which will then be sorted
        AnyChannels::sorted(smallvec![ y, a ]),
    );

    let image = Image::from_single_layer(layer);
    image.write().to_file(path).unwrap();
```

Have a look at [FlatSamples](https://docs.rs/exr/1.0.0/exr/image/enum.FlatSamples.html) to see how the two-dimensional pixels must be arranged into the one-dimensional `vec![0.0; pixel_count]`, as they must be arranged in a single vector row after row. Note that I'm currently working on an API that allows you work with pixels (for example, `(0.2, 0.4, 0.1)`) instead of these flattened arrays, much like the RGBA API currently does.

**Comment by johannesvollmer** [comment]
Does this help? Where would have a little more documentation helped you? Where should a little hint be added?

**Comment by virtualritz** [comment]
Yes, that helps!
I think have my pixels arranged like that (rows) in a flat, `f32` buffer originally, from the renderer. 
I.e. let's say I have two layers, albedo & normal. The `f32` buffer I get from the renderer is `width*height*6` `f32`s like so:

`albedo.r, albedo.g, albedo.b, normal.x, normal.y, normal.z, albedo.r, albedo.g, albedo.b, normal.x, normal.y, normal.z, ...`

Is that what you mean by a `FlatSample`?

**Comment by johannesvollmer** [comment]
With the approach I suggested above, it is required to provide separate buffers for each channel. Unfortunately, this means that you will have to split up your buffers into separate buffers until the new API is ready, like this for an image with albedo and normals:

`let albedo_red_channel = [r, r, r, r, ...]`
`let albedo_green_channel = [g, g, g, g, ...]`
`let albedo_blue_channel = [b, b, b, b, ...]`
`let normal_x_channel = [x, x, x, x, ...]`
`let normal_y_channel = [y, y, y, y, ...]`
`let normal_z_channel = [z, z, z, z, ...]`
And within each channel, the samples are arranged row after row (left to right), from bottom row to the top row.

`Sample`, in this context, is a single component of a single pixel, for example the green component of the upper left pixel.
`FlatSample` is a sample that does not store multiple values (sometimes called deep data).

**Comment by johannesvollmer** [comment]
I've just merged the new API into `dev`, only a few days until it this will be released :)
